# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Chart-Gnuplot
version:      0.07
version_from: lib/Chart/Gnuplot.pm
installdirs:  site
requires:
    File::Copy:                    2.08
    File::Temp:                    0.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
