#!/usr/bin/perl

use strict;
use warnings;
my $bl = "$ENV{SEEKER_HOME}/AnalysisScripts/benchlist";
my @bench;
open BL,"$bl" or die "Could not open $bl\n";
chomp(@bench = <BL>);
close(BL);
foreach my $b (@bench){
	print "$b\n";
	my @data;
	for(my $i=0;$i<5;$i++){
		my $f = "./S$i/$b.ich";
		open S,$f or die "Could not open $f\n";
		my $trash = <S>;
		my $j = 0;
		while(my $line = <S>){
			chomp($line);
			my @tmp = split(/\s/,$line);
			my $tot_inst = $tmp[0];
			my $reipc = $tmp[1];
			my $rfipc = $tmp[2];
			$data[$j++] .= "$reipc,$rfipc" if($i == 0);
			$data[$j++] .= ",$reipc,$rfipc" if($i != 0);
		}
		close(S);
	}
	open O,"+>$b.tch" or die "Could not create $b.tch\n";
	foreach my $line (@data){
		print O "$line\n";
	}
	close(O);
}

